//
//  lettresender
//
//  Created by Amine Bensalah on 27/10/2016.
//  Copyright © 2016 Amine Bensalah. All rights reserved.
//

import Foundation

public enum Ionicons: String {
    case alert = "\u{f101}"
    case alertCircled = "\u{f100}"
    case androidAdd = "\u{f2c7}"
    case androidAddCircle = "\u{f359}"
    case androidAlarmClock = "\u{f35a}"
    case androidAlert = "\u{f35b}"
    case androidApps = "\u{f35c}"
    case androidArchive = "\u{f2c9}"
    case androidArrowBack = "\u{f2ca}"
    case androidArrowDown = "\u{f35d}"
    case androidArrowDropdown = "\u{f35f}"
    case androidArrowDropdownCircle = "\u{f35e}"
    case androidArrowDropleft = "\u{f361}"
    case androidArrowDropleftCircle = "\u{f360}"
    case androidArrowDropright = "\u{f363}"
    case androidArrowDroprightCircle = "\u{f362}"
    case androidArrowDropup = "\u{f365}"
    case androidArrowDropupCircle = "\u{f364}"
    case androidArrowForward = "\u{f30f}"
    case androidArrowUp = "\u{f366}"
    case androidAttach = "\u{f367}"
    case androidBar = "\u{f368}"
    case androidBicycle = "\u{f369}"
    case androidBoat = "\u{f36a}"
    case androidBookmark = "\u{f36b}"
    case androidBulb = "\u{f36c}"
    case androidBus = "\u{f36d}"
    case androidCalendar = "\u{f2d1}"
    case androidCall = "\u{f2d2}"
    case androidCamera = "\u{f2d3}"
    case androidCancel = "\u{f36e}"
    case androidCar = "\u{f36f}"
    case androidCart = "\u{f370}"
    case androidChat = "\u{f2d4}"
    case androidCheckbox = "\u{f374}"
    case androidCheckboxBlank = "\u{f371}"
    case androidCheckboxOutline = "\u{f373}"
    case androidCheckboxOutlineBlank = "\u{f372}"
    case androidCheckmarkCircle = "\u{f375}"
    case androidClipboard = "\u{f376}"
    case androidClose = "\u{f2d7}"
    case androidCloud = "\u{f37a}"
    case androidCloudCircle = "\u{f377}"
    case androidCloudDone = "\u{f378}"
    case androidCloudOutline = "\u{f379}"
    case androidColorPalette = "\u{f37b}"
    case androidCompass = "\u{f37c}"
    case androidContact = "\u{f2d8}"
    case androidContacts = "\u{f2d9}"
    case androidContract = "\u{f37d}"
    case androidCreate = "\u{f37e}"
    case androidDelete = "\u{f37f}"
    case androidDesktop = "\u{f380}"
    case androidDocument = "\u{f381}"
    case androidDone = "\u{f383}"
    case androidDoneAll = "\u{f382}"
    case androidDownload = "\u{f2dd}"
    case androidDrafts = "\u{f384}"
    case androidExit = "\u{f385}"
    case androidExpand = "\u{f386}"
    case androidFavorite = "\u{f388}"
    case androidFavoriteOutline = "\u{f387}"
    case androidFilm = "\u{f389}"
    case androidFolder = "\u{f2e0}"
    case androidFolderOpen = "\u{f38a}"
    case androidFunnel = "\u{f38b}"
    case androidGlobe = "\u{f38c}"
    case androidHand = "\u{f2e3}"
    case androidHangout = "\u{f38d}"
    case androidHappy = "\u{f38e}"
    case androidHome = "\u{f38f}"
    case androidImage = "\u{f2e4}"
    case androidLaptop = "\u{f390}"
    case androidList = "\u{f391}"
    case androidLocate = "\u{f2e9}"
    case androidLock = "\u{f392}"
    case androidMail = "\u{f2eb}"
    case androidMap = "\u{f393}"
    case androidMenu = "\u{f394}"
    case androidMicrophone = "\u{f2ec}"
    case androidMicrophoneOff = "\u{f395}"
    case androidMoreHorizontal = "\u{f396}"
    case androidMoreVertical = "\u{f397}"
    case androidNavigate = "\u{f398}"
    case androidNotifications = "\u{f39b}"
    case androidNotificationsNone = "\u{f399}"
    case androidNotificationsOff = "\u{f39a}"
    case androidOpen = "\u{f39c}"
    case androidOptions = "\u{f39d}"
    case androidPeople = "\u{f39e}"
    case androidPerson = "\u{f3a0}"
    case androidPersonAdd = "\u{f39f}"
    case androidPhoneLandscape = "\u{f3a1}"
    case androidPhonePortrait = "\u{f3a2}"
    case androidPin = "\u{f3a3}"
    case androidPlane = "\u{f3a4}"
    case androidPlaystore = "\u{f2f0}"
    case androidPrint = "\u{f3a5}"
    case androidRadioButtonOff = "\u{f3a6}"
    case androidRadioButtonOn = "\u{f3a7}"
    case androidRefresh = "\u{f3a8}"
    case androidRemove = "\u{f2f4}"
    case androidRemoveCircle = "\u{f3a9}"
    case androidRestaurant = "\u{f3aa}"
    case androidSad = "\u{f3ab}"
    case androidSearch = "\u{f2f5}"
    case androidSend = "\u{f2f6}"
    case androidSettings = "\u{f2f7}"
    case androidShare = "\u{f2f8}"
    case androidShareAlt = "\u{f3ac}"
    case androidStar = "\u{f2fc}"
    case androidStarHalf = "\u{f3ad}"
    case androidStarOutline = "\u{f3ae}"
    case androidStopwatch = "\u{f2fd}"
    case androidSubway = "\u{f3af}"
    case androidSunny = "\u{f3b0}"
    case androidSync = "\u{f3b1}"
    case androidTextsms = "\u{f3b2}"
    case androidTime = "\u{f3b3}"
    case androidTrain = "\u{f3b4}"
    case androidUnlock = "\u{f3b5}"
    case androidUpload = "\u{f3b6}"
    case androidVolumeDown = "\u{f3b7}"
    case androidVolumeMute = "\u{f3b8}"
    case androidVolumeOff = "\u{f3b9}"
    case androidVolumeUp = "\u{f3ba}"
    case androidWalk = "\u{f3bb}"
    case androidWarning = "\u{f3bc}"
    case androidWatch = "\u{f3bd}"
    case androidWifi = "\u{f305}"
    case aperture = "\u{f313}"
    case archive = "\u{f102}"
    case arrowDownA = "\u{f103}"
    case arrowDownB = "\u{f104}"
    case arrowDownC = "\u{f105}"
    case arrowExpand = "\u{f25e}"
    case arrowGraphDownLeft = "\u{f25f}"
    case arrowGraphDownRight = "\u{f260}"
    case arrowGraphUpLeft = "\u{f261}"
    case arrowGraphUpRight = "\u{f262}"
    case arrowLeftA = "\u{f106}"
    case arrowLeftB = "\u{f107}"
    case arrowLeftC = "\u{f108}"
    case arrowMove = "\u{f263}"
    case arrowResize = "\u{f264}"
    case arrowReturnLeft = "\u{f265}"
    case arrowReturnRight = "\u{f266}"
    case arrowRightA = "\u{f109}"
    case arrowRightB = "\u{f10a}"
    case arrowRightC = "\u{f10b}"
    case arrowShrink = "\u{f267}"
    case arrowSwap = "\u{f268}"
    case arrowUpA = "\u{f10c}"
    case arrowUpB = "\u{f10d}"
    case arrowUpC = "\u{f10e}"
    case asterisk = "\u{f314}"
    case at = "\u{f10f}"
    case backspace = "\u{f3bf}"
    case backspaceOutline = "\u{f3be}"
    case bag = "\u{f110}"
    case batteryCharging = "\u{f111}"
    case batteryEmpty = "\u{f112}"
    case batteryFull = "\u{f113}"
    case batteryHalf = "\u{f114}"
    case batteryLow = "\u{f115}"
    case beaker = "\u{f269}"
    case beer = "\u{f26a}"
    case bluetooth = "\u{f116}"
    case bonfire = "\u{f315}"
    case bookmark = "\u{f26b}"
    case bowtie = "\u{f3c0}"
    case briefcase = "\u{f26c}"
    case bug = "\u{f2be}"
    case calculator = "\u{f26d}"
    case calendar = "\u{f117}"
    case camera = "\u{f118}"
    case card = "\u{f119}"
    case cash = "\u{f316}"
    case chatbox = "\u{f11b}"
    case chatboxWorking = "\u{f11a}"
    case chatboxes = "\u{f11c}"
    case chatbubble = "\u{f11e}"
    case chatbubbleWorking = "\u{f11d}"
    case chatbubbles = "\u{f11f}"
    case checkmark = "\u{f122}"
    case checkmarkCircled = "\u{f120}"
    case checkmarkRound = "\u{f121}"
    case chevronDown = "\u{f123}"
    case chevronLeft = "\u{f124}"
    case chevronRight = "\u{f125}"
    case chevronUp = "\u{f126}"
    case clipboard = "\u{f127}"
    case clock = "\u{f26e}"
    case close = "\u{f12a}"
    case closeCircled = "\u{f128}"
    case closeRound = "\u{f129}"
    case closedCaptioning = "\u{f317}"
    case cloud = "\u{f12b}"
    case code = "\u{f271}"
    case codeDownload = "\u{f26f}"
    case codeWorking = "\u{f270}"
    case coffee = "\u{f272}"
    case compass = "\u{f273}"
    case compose = "\u{f12c}"
    case connectionBars = "\u{f274}"
    case contrast = "\u{f275}"
    case crop = "\u{f3c1}"
    case cube = "\u{f318}"
    case disc = "\u{f12d}"
    case document = "\u{f12f}"
    case documentText = "\u{f12e}"
    case drag = "\u{f130}"
    case earth = "\u{f276}"
    case easel = "\u{f3c2}"
    case edit = "\u{f2bf}"
    case egg = "\u{f277}"
    case eject = "\u{f131}"
    case email = "\u{f132}"
    case emailUnread = "\u{f3c3}"
    case erlenmeyerFlask = "\u{f3c5}"
    case erlenmeyerFlaskBubbles = "\u{f3c4}"
    case eye = "\u{f133}"
    case eyeDisabled = "\u{f306}"
    case female = "\u{f278}"
    case filing = "\u{f134}"
    case filmMarker = "\u{f135}"
    case fireball = "\u{f319}"
    case flag = "\u{f279}"
    case flame = "\u{f31a}"
    case flash = "\u{f137}"
    case flashOff = "\u{f136}"
    case folder = "\u{f139}"
    case fork = "\u{f27a}"
    case forkRepo = "\u{f2c0}"
    case forward = "\u{f13a}"
    case funnel = "\u{f31b}"
    case gearA = "\u{f13d}"
    case gearB = "\u{f13e}"
    case grid = "\u{f13f}"
    case hammer = "\u{f27b}"
    case happy = "\u{f31c}"
    case happyOutline = "\u{f3c6}"
    case headphone = "\u{f140}"
    case heart = "\u{f141}"
    case heartBroken = "\u{f31d}"
    case help = "\u{f143}"
    case helpBuoy = "\u{f27c}"
    case helpCircled = "\u{f142}"
    case home = "\u{f144}"
    case icecream = "\u{f27d}"
    case image = "\u{f147}"
    case images = "\u{f148}"
    case information = "\u{f14a}"
    case informationCircled = "\u{f149}"
    case ionic = "\u{f14b}"
    case iosAlarm = "\u{f3c8}"
    case iosAlarmOutline = "\u{f3c7}"
    case iosAlbums = "\u{f3ca}"
    case iosAlbumsOutline = "\u{f3c9}"
    case iosAmericanfootball = "\u{f3cc}"
    case iosAmericanfootballOutline = "\u{f3cb}"
    case iosAnalytics = "\u{f3ce}"
    case iosAnalyticsOutline = "\u{f3cd}"
    case iosArrowBack = "\u{f3cf}"
    case iosArrowDown = "\u{f3d0}"
    case iosArrowForward = "\u{f3d1}"
    case iosArrowLeft = "\u{f3d2}"
    case iosArrowRight = "\u{f3d3}"
    case iosArrowThinDown = "\u{f3d4}"
    case iosArrowThinLeft = "\u{f3d5}"
    case iosArrowThinRight = "\u{f3d6}"
    case iosArrowThinUp = "\u{f3d7}"
    case iosArrowUp = "\u{f3d8}"
    case iosAt = "\u{f3da}"
    case iosAtOutline = "\u{f3d9}"
    case iosBarcode = "\u{f3dc}"
    case iosBarcodeOutline = "\u{f3db}"
    case iosBaseball = "\u{f3de}"
    case iosBaseballOutline = "\u{f3dd}"
    case iosBasketball = "\u{f3e0}"
    case iosBasketballOutline = "\u{f3df}"
    case iosBell = "\u{f3e2}"
    case iosBellOutline = "\u{f3e1}"
    case iosBody = "\u{f3e4}"
    case iosBodyOutline = "\u{f3e3}"
    case iosBolt = "\u{f3e6}"
    case iosBoltOutline = "\u{f3e5}"
    case iosBook = "\u{f3e8}"
    case iosBookOutline = "\u{f3e7}"
    case iosBookmarks = "\u{f3ea}"
    case iosBookmarksOutline = "\u{f3e9}"
    case iosBox = "\u{f3ec}"
    case iosBoxOutline = "\u{f3eb}"
    case iosBriefcase = "\u{f3ee}"
    case iosBriefcaseOutline = "\u{f3ed}"
    case iosBrowsers = "\u{f3f0}"
    case iosBrowsersOutline = "\u{f3ef}"
    case iosCalculator = "\u{f3f2}"
    case iosCalculatorOutline = "\u{f3f1}"
    case iosCalendar = "\u{f3f4}"
    case iosCalendarOutline = "\u{f3f3}"
    case iosCamera = "\u{f3f6}"
    case iosCameraOutline = "\u{f3f5}"
    case iosCart = "\u{f3f8}"
    case iosCartOutline = "\u{f3f7}"
    case iosChatboxes = "\u{f3fa}"
    case iosChatboxesOutline = "\u{f3f9}"
    case iosChatbubble = "\u{f3fc}"
    case iosChatbubbleOutline = "\u{f3fb}"
    case iosCheckmark = "\u{f3ff}"
    case iosCheckmarkEmpty = "\u{f3fd}"
    case iosCheckmarkOutline = "\u{f3fe}"
    case iosCircleFilled = "\u{f400}"
    case iosCircleOutline = "\u{f401}"
    case iosClock = "\u{f403}"
    case iosClockOutline = "\u{f402}"
    case iosClose = "\u{f406}"
    case iosCloseEmpty = "\u{f404}"
    case iosCloseOutline = "\u{f405}"
    case iosCloud = "\u{f40c}"
    case iosCloudDownload = "\u{f408}"
    case iosCloudDownloadOutline = "\u{f407}"
    case iosCloudOutline = "\u{f409}"
    case iosCloudUpload = "\u{f40b}"
    case iosCloudUploadOutline = "\u{f40a}"
    case iosCloudy = "\u{f410}"
    case iosCloudyNight = "\u{f40e}"
    case iosCloudyNightOutline = "\u{f40d}"
    case iosCloudyOutline = "\u{f40f}"
    case iosCog = "\u{f412}"
    case iosCogOutline = "\u{f411}"
    case iosColorFilter = "\u{f414}"
    case iosColorFilterOutline = "\u{f413}"
    case iosColorWand = "\u{f416}"
    case iosColorWandOutline = "\u{f415}"
    case iosCompose = "\u{f418}"
    case iosComposeOutline = "\u{f417}"
    case iosContact = "\u{f41a}"
    case iosContactOutline = "\u{f419}"
    case iosCopy = "\u{f41c}"
    case iosCopyOutline = "\u{f41b}"
    case iosCrop = "\u{f41e}"
    case iosCropStrong = "\u{f41d}"
    case iosDownload = "\u{f420}"
    case iosDownloadOutline = "\u{f41f}"
    case iosDrag = "\u{f421}"
    case iosEmail = "\u{f423}"
    case iosEmailOutline = "\u{f422}"
    case iosEye = "\u{f425}"
    case iosEyeOutline = "\u{f424}"
    case iosFastforward = "\u{f427}"
    case iosFastforwardOutline = "\u{f426}"
    case iosFiling = "\u{f429}"
    case iosFilingOutline = "\u{f428}"
    case iosFilm = "\u{f42b}"
    case iosFilmOutline = "\u{f42a}"
    case iosFlag = "\u{f42d}"
    case iosFlagOutline = "\u{f42c}"
    case iosFlame = "\u{f42f}"
    case iosFlameOutline = "\u{f42e}"
    case iosFlask = "\u{f431}"
    case iosFlaskOutline = "\u{f430}"
    case iosFlower = "\u{f433}"
    case iosFlowerOutline = "\u{f432}"
    case iosFolder = "\u{f435}"
    case iosFolderOutline = "\u{f434}"
    case iosFootball = "\u{f437}"
    case iosFootballOutline = "\u{f436}"
    case iosGameControllerA = "\u{f439}"
    case iosGameControllerAOutline = "\u{f438}"
    case iosGameControllerB = "\u{f43b}"
    case iosGameControllerBOutline = "\u{f43a}"
    case iosGear = "\u{f43d}"
    case iosGearOutline = "\u{f43c}"
    case iosGlasses = "\u{f43f}"
    case iosGlassesOutline = "\u{f43e}"
    case iosGridView = "\u{f441}"
    case iosGridViewOutline = "\u{f440}"
    case iosHeart = "\u{f443}"
    case iosHeartOutline = "\u{f442}"
    case iosHelp = "\u{f446}"
    case iosHelpEmpty = "\u{f444}"
    case iosHelpOutline = "\u{f445}"
    case iosHome = "\u{f448}"
    case iosHomeOutline = "\u{f447}"
    case iosInfinite = "\u{f44a}"
    case iosInfiniteOutline = "\u{f449}"
    case iosInformation = "\u{f44d}"
    case iosInformationEmpty = "\u{f44b}"
    case iosInformationOutline = "\u{f44c}"
    case iosIonicOutline = "\u{f44e}"
    case iosKeypad = "\u{f450}"
    case iosKeypadOutline = "\u{f44f}"
    case iosLightbulb = "\u{f452}"
    case iosLightbulbOutline = "\u{f451}"
    case iosList = "\u{f454}"
    case iosListOutline = "\u{f453}"
    case iosLocation = "\u{f456}"
    case iosLocationOutline = "\u{f455}"
    case iosLocked = "\u{f458}"
    case iosLockedOutline = "\u{f457}"
    case iosLoop = "\u{f45a}"
    case iosLoopStrong = "\u{f459}"
    case iosMedical = "\u{f45c}"
    case iosMedicalOutline = "\u{f45b}"
    case iosMedkit = "\u{f45e}"
    case iosMedkitOutline = "\u{f45d}"
    case iosMic = "\u{f461}"
    case iosMicOff = "\u{f45f}"
    case iosMicOutline = "\u{f460}"
    case iosMinus = "\u{f464}"
    case iosMinusEmpty = "\u{f462}"
    case iosMinusOutline = "\u{f463}"
    case iosMonitor = "\u{f466}"
    case iosMonitorOutline = "\u{f465}"
    case iosMoon = "\u{f468}"
    case iosMoonOutline = "\u{f467}"
    case iosMore = "\u{f46a}"
    case iosMoreOutline = "\u{f469}"
    case iosMusicalNote = "\u{f46b}"
    case iosMusicalNotes = "\u{f46c}"
    case iosNavigate = "\u{f46e}"
    case iosNavigateOutline = "\u{f46d}"
    case iosNutrition = "\u{f470}"
    case iosNutritionOutline = "\u{f46f}"
    case iosPaper = "\u{f472}"
    case iosPaperOutline = "\u{f471}"
    case iosPaperplane = "\u{f474}"
    case iosPaperplaneOutline = "\u{f473}"
    case iosPartlysunny = "\u{f476}"
    case iosPartlysunnyOutline = "\u{f475}"
    case iosPause = "\u{f478}"
    case iosPauseOutline = "\u{f477}"
    case iosPaw = "\u{f47a}"
    case iosPawOutline = "\u{f479}"
    case iosPeople = "\u{f47c}"
    case iosPeopleOutline = "\u{f47b}"
    case iosPerson = "\u{f47e}"
    case iosPersonOutline = "\u{f47d}"
    case iosPersonadd = "\u{f480}"
    case iosPersonaddOutline = "\u{f47f}"
    case iosPhotos = "\u{f482}"
    case iosPhotosOutline = "\u{f481}"
    case iosPie = "\u{f484}"
    case iosPieOutline = "\u{f483}"
    case iosPint = "\u{f486}"
    case iosPintOutline = "\u{f485}"
    case iosPlay = "\u{f488}"
    case iosPlayOutline = "\u{f487}"
    case iosPlus = "\u{f48b}"
    case iosPlusEmpty = "\u{f489}"
    case iosPlusOutline = "\u{f48a}"
    case iosPricetag = "\u{f48d}"
    case iosPricetagOutline = "\u{f48c}"
    case iosPricetags = "\u{f48f}"
    case iosPricetagsOutline = "\u{f48e}"
    case iosPrinter = "\u{f491}"
    case iosPrinterOutline = "\u{f490}"
    case iosPulse = "\u{f493}"
    case iosPulseStrong = "\u{f492}"
    case iosRainy = "\u{f495}"
    case iosRainyOutline = "\u{f494}"
    case iosRecording = "\u{f497}"
    case iosRecordingOutline = "\u{f496}"
    case iosRedo = "\u{f499}"
    case iosRedoOutline = "\u{f498}"
    case iosRefresh = "\u{f49c}"
    case iosRefreshEmpty = "\u{f49a}"
    case iosRefreshOutline = "\u{f49b}"
    case iosReload = "\u{f49d}"
    case iosReverseCamera = "\u{f49f}"
    case iosReverseCameraOutline = "\u{f49e}"
    case iosRewind = "\u{f4a1}"
    case iosRewindOutline = "\u{f4a0}"
    case iosRose = "\u{f4a3}"
    case iosRoseOutline = "\u{f4a2}"
    case iosSearch = "\u{f4a5}"
    case iosSearchStrong = "\u{f4a4}"
    case iosSettings = "\u{f4a7}"
    case iosSettingsStrong = "\u{f4a6}"
    case iosShuffle = "\u{f4a9}"
    case iosShuffleStrong = "\u{f4a8}"
    case iosSkipbackward = "\u{f4ab}"
    case iosSkipbackwardOutline = "\u{f4aa}"
    case iosSkipforward = "\u{f4ad}"
    case iosSkipforwardOutline = "\u{f4ac}"
    case iosSnowy = "\u{f4ae}"
    case iosSpeedometer = "\u{f4b0}"
    case iosSpeedometerOutline = "\u{f4af}"
    case iosStar = "\u{f4b3}"
    case iosStarHalf = "\u{f4b1}"
    case iosStarOutline = "\u{f4b2}"
    case iosStopwatch = "\u{f4b5}"
    case iosStopwatchOutline = "\u{f4b4}"
    case iosSunny = "\u{f4b7}"
    case iosSunnyOutline = "\u{f4b6}"
    case iosTelephone = "\u{f4b9}"
    case iosTelephoneOutline = "\u{f4b8}"
    case iosTennisball = "\u{f4bb}"
    case iosTennisballOutline = "\u{f4ba}"
    case iosThunderstorm = "\u{f4bd}"
    case iosThunderstormOutline = "\u{f4bc}"
    case iosTime = "\u{f4bf}"
    case iosTimeOutline = "\u{f4be}"
    case iosTimer = "\u{f4c1}"
    case iosTimerOutline = "\u{f4c0}"
    case iosToggle = "\u{f4c3}"
    case iosToggleOutline = "\u{f4c2}"
    case iosTrash = "\u{f4c5}"
    case iosTrashOutline = "\u{f4c4}"
    case iosUndo = "\u{f4c7}"
    case iosUndoOutline = "\u{f4c6}"
    case iosUnlocked = "\u{f4c9}"
    case iosUnlockedOutline = "\u{f4c8}"
    case iosUpload = "\u{f4cb}"
    case iosUploadOutline = "\u{f4ca}"
    case iosVideocam = "\u{f4cd}"
    case iosVideocamOutline = "\u{f4cc}"
    case iosVolumeHigh = "\u{f4ce}"
    case iosVolumeLow = "\u{f4cf}"
    case iosWineglass = "\u{f4d1}"
    case iosWineglassOutline = "\u{f4d0}"
    case iosWorld = "\u{f4d3}"
    case iosWorldOutline = "\u{f4d2}"
    case ipad = "\u{f1f9}"
    case iphone = "\u{f1fa}"
    case ipod = "\u{f1fb}"
    case jet = "\u{f295}"
    case key = "\u{f296}"
    case knife = "\u{f297}"
    case laptop = "\u{f1fc}"
    case leaf = "\u{f1fd}"
    case levels = "\u{f298}"
    case lightbulb = "\u{f299}"
    case link = "\u{f1fe}"
    case loadA = "\u{f29a}"
    case loadB = "\u{f29b}"
    case loadC = "\u{f29c}"
    case loadD = "\u{f29d}"
    case location = "\u{f1ff}"
    case lockCombination = "\u{f4d4}"
    case locked = "\u{f200}"
    case logIn = "\u{f29e}"
    case logOut = "\u{f29f}"
    case loop = "\u{f201}"
    case magnet = "\u{f2a0}"
    case male = "\u{f2a1}"
    case man = "\u{f202}"
    case map = "\u{f203}"
    case medkit = "\u{f2a2}"
    case merge = "\u{f33f}"
    case micA = "\u{f204}"
    case micB = "\u{f205}"
    case micC = "\u{f206}"
    case minus = "\u{f209}"
    case minusCircled = "\u{f207}"
    case minusRound = "\u{f208}"
    case modelS = "\u{f2c1}"
    case monitor = "\u{f20a}"
    case more = "\u{f20b}"
    case mouse = "\u{f340}"
    case musicNote = "\u{f20c}"
    case navicon = "\u{f20e}"
    case naviconRound = "\u{f20d}"
    case navigate = "\u{f2a3}"
    case network = "\u{f341}"
    case noSmoking = "\u{f2c2}"
    case nuclear = "\u{f2a4}"
    case outlet = "\u{f342}"
    case paintbrush = "\u{f4d5}"
    case paintbucket = "\u{f4d6}"
    case paperAirplane = "\u{f2c3}"
    case paperclip = "\u{f20f}"
    case pause = "\u{f210}"
    case person = "\u{f213}"
    case personAdd = "\u{f211}"
    case personStalker = "\u{f212}"
    case pieGraph = "\u{f2a5}"
    case pin = "\u{f2a6}"
    case pinpoint = "\u{f2a7}"
    case pizza = "\u{f2a8}"
    case plane = "\u{f214}"
    case planet = "\u{f343}"
    case play = "\u{f215}"
    case playstation = "\u{f30a}"
    case plus = "\u{f218}"
    case plusCircled = "\u{f216}"
    case plusRound = "\u{f217}"
    case podium = "\u{f344}"
    case pound = "\u{f219}"
    case power = "\u{f2a9}"
    case pricetag = "\u{f2aa}"
    case pricetags = "\u{f2ab}"
    case printer = "\u{f21a}"
    case pullRequest = "\u{f345}"
    case qrScanner = "\u{f346}"
    case quote = "\u{f347}"
    case radioWaves = "\u{f2ac}"
    case record = "\u{f21b}"
    case refresh = "\u{f21c}"
    case reply = "\u{f21e}"
    case replyAll = "\u{f21d}"
    case ribbonA = "\u{f348}"
    case ribbonB = "\u{f349}"
    case sad = "\u{f34a}"
    case sadOutline = "\u{f4d7}"
    case scissors = "\u{f34b}"
    case search = "\u{f21f}"
    case settings = "\u{f2ad}"
    case share = "\u{f220}"
    case shuffle = "\u{f221}"
    case skipBackward = "\u{f222}"
    case skipForward = "\u{f223}"
    case socialAndroid = "\u{f225}"
    case socialAndroidOutline = "\u{f224}"
    case socialAngular = "\u{f4d9}"
    case socialAngularOutline = "\u{f4d8}"
    case socialApple = "\u{f227}"
    case socialAppleOutline = "\u{f226}"
    case socialBitcoin = "\u{f2af}"
    case socialBitcoinOutline = "\u{f2ae}"
    case socialBuffer = "\u{f229}"
    case socialBufferOutline = "\u{f228}"
    case socialChrome = "\u{f4db}"
    case socialChromeOutline = "\u{f4da}"
    case socialCodepen = "\u{f4dd}"
    case socialCodepenOutline = "\u{f4dc}"
    case socialCss3 = "\u{f4df}"
    case socialCss3Outline = "\u{f4de}"
    case socialDesignernews = "\u{f22b}"
    case socialDesignernewsOutline = "\u{f22a}"
    case socialDribbble = "\u{f22d}"
    case socialDribbbleOutline = "\u{f22c}"
    case socialDropbox = "\u{f22f}"
    case socialDropboxOutline = "\u{f22e}"
    case socialEuro = "\u{f4e1}"
    case socialEuroOutline = "\u{f4e0}"
    case socialFacebook = "\u{f231}"
    case socialFacebookOutline = "\u{f230}"
    case socialFoursquare = "\u{f34d}"
    case socialFoursquareOutline = "\u{f34c}"
    case socialFreebsdDevil = "\u{f2c4}"
    case socialGithub = "\u{f233}"
    case socialGithubOutline = "\u{f232}"
    case socialGoogle = "\u{f34f}"
    case socialGoogleOutline = "\u{f34e}"
    case socialGoogleplus = "\u{f235}"
    case socialGoogleplusOutline = "\u{f234}"
    case socialHackernews = "\u{f237}"
    case socialHackernewsOutline = "\u{f236}"
    case socialHtml5 = "\u{f4e3}"
    case socialHtml5Outline = "\u{f4e2}"
    case socialInstagram = "\u{f351}"
    case socialInstagramOutline = "\u{f350}"
    case socialJavascript = "\u{f4e5}"
    case socialJavascriptOutline = "\u{f4e4}"
    case socialLinkedin = "\u{f239}"
    case socialLinkedinOutline = "\u{f238}"
    case socialMarkdown = "\u{f4e6}"
    case socialNodejs = "\u{f4e7}"
    case socialOctocat = "\u{f4e8}"
    case socialPinterest = "\u{f2b1}"
    case socialPinterestOutline = "\u{f2b0}"
    case socialPython = "\u{f4e9}"
    case socialReddit = "\u{f23b}"
    case socialRedditOutline = "\u{f23a}"
    case socialRss = "\u{f23d}"
    case socialRssOutline = "\u{f23c}"
    case socialSass = "\u{f4ea}"
    case socialSkype = "\u{f23f}"
    case socialSkypeOutline = "\u{f23e}"
    case socialSnapchat = "\u{f4ec}"
    case socialSnapchatOutline = "\u{f4eb}"
    case socialTumblr = "\u{f241}"
    case socialTumblrOutline = "\u{f240}"
    case socialTux = "\u{f2c5}"
    case socialTwitch = "\u{f4ee}"
    case socialTwitchOutline = "\u{f4ed}"
    case socialTwitter = "\u{f243}"
    case socialTwitterOutline = "\u{f242}"
    case socialUsd = "\u{f353}"
    case socialUsdOutline = "\u{f352}"
    case socialVimeo = "\u{f245}"
    case socialVimeoOutline = "\u{f244}"
    case socialWhatsapp = "\u{f4f0}"
    case socialWhatsappOutline = "\u{f4ef}"
    case socialWindows = "\u{f247}"
    case socialWindowsOutline = "\u{f246}"
    case socialWordpress = "\u{f249}"
    case socialWordpressOutline = "\u{f248}"
    case socialYahoo = "\u{f24b}"
    case socialYahooOutline = "\u{f24a}"
    case socialYen = "\u{f4f2}"
    case socialYenOutline = "\u{f4f1}"
    case socialYoutube = "\u{f24d}"
    case socialYoutubeOutline = "\u{f24c}"
    case soupCan = "\u{f4f4}"
    case soupCanOutline = "\u{f4f3}"
    case speakerphone = "\u{f2b2}"
    case speedometer = "\u{f2b3}"
    case spoon = "\u{f2b4}"
    case star = "\u{f24e}"
    case statsBars = "\u{f2b5}"
    case steam = "\u{f30b}"
    case stop = "\u{f24f}"
    case thermometer = "\u{f2b6}"
    case thumbsdown = "\u{f250}"
    case thumbsup = "\u{f251}"
    case toggle = "\u{f355}"
    case toggleFilled = "\u{f354}"
    case transgender = "\u{f4f5}"
    case trashA = "\u{f252}"
    case trashB = "\u{f253}"
    case trophy = "\u{f356}"
    case tshirt = "\u{f4f7}"
    case tshirtOutline = "\u{f4f6}"
    case umbrella = "\u{f2b7}"
    case university = "\u{f357}"
    case unlocked = "\u{f254}"
    case upload = "\u{f255}"
    case usb = "\u{f2b8}"
    case videocamera = "\u{f256}"
    case volumeHigh = "\u{f257}"
    case volumeLow = "\u{f258}"
    case volumeMedium = "\u{f259}"
    case volumeMute = "\u{f25a}"
    case wand = "\u{f358}"
    case waterdrop = "\u{f25b}"
    case wifi = "\u{f25c}"
    case wineglass = "\u{f2b9}"
    case woman = "\u{f25d}"
    case wrench = "\u{f2ba}"
    case xbox = "\u{f30c}"
    
    public init?(rawValue: String) {
        switch rawValue {
        case "alert" : self = .alert
        case "alertCircled" : self = .alertCircled
        case "androidAdd" : self = .androidAdd
        case "androidAddCircle" : self = .androidAddCircle
        case "androidAlarmClock" : self = .androidAlarmClock
        case "androidAlert" : self = .androidAlert
        case "androidApps" : self = .androidApps
        case "androidArchive" : self = .androidArchive
        case "androidArrowBack" : self = .androidArrowBack
        case "androidArrowDown" : self = .androidArrowDown
        case "androidArrowDropdown" : self = .androidArrowDropdown
        case "androidArrowDropdownCircle" : self = .androidArrowDropdownCircle
        case "androidArrowDropleft" : self = .androidArrowDropleft
        case "androidArrowDropleftCircle" : self = .androidArrowDropleftCircle
        case "androidArrowDropright" : self = .androidArrowDropright
        case "androidArrowDroprightCircle" : self = .androidArrowDroprightCircle
        case "androidArrowDropup" : self = .androidArrowDropup
        case "androidArrowDropupCircle" : self = .androidArrowDropupCircle
        case "androidArrowForward" : self = .androidArrowForward
        case "androidArrowUp" : self = .androidArrowUp
        case "androidAttach" : self = .androidAttach
        case "androidBar" : self = .androidBar
        case "androidBicycle" : self = .androidBicycle
        case "androidBoat" : self = .androidBoat
        case "androidBookmark" : self = .androidBookmark
        case "androidBulb" : self = .androidBulb
        case "androidBus" : self = .androidBus
        case "androidCalendar" : self = .androidCalendar
        case "androidCall" : self = .androidCall
        case "androidCamera" : self = .androidCamera
        case "androidCancel" : self = .androidCancel
        case "androidCar" : self = .androidCar
        case "androidCart" : self = .androidCart
        case "androidChat" : self = .androidChat
        case "androidCheckbox" : self = .androidCheckbox
        case "androidCheckboxBlank" : self = .androidCheckboxBlank
        case "androidCheckboxOutline" : self = .androidCheckboxOutline
        case "androidCheckboxOutlineBlank" : self = .androidCheckboxOutlineBlank
        case "androidCheckmarkCircle" : self = .androidCheckmarkCircle
        case "androidClipboard" : self = .androidClipboard
        case "androidClose" : self = .androidClose
        case "androidCloud" : self = .androidCloud
        case "androidCloudCircle" : self = .androidCloudCircle
        case "androidCloudDone" : self = .androidCloudDone
        case "androidCloudOutline" : self = .androidCloudOutline
        case "androidColorPalette" : self = .androidColorPalette
        case "androidCompass" : self = .androidCompass
        case "androidContact" : self = .androidContact
        case "androidContacts" : self = .androidContacts
        case "androidContract" : self = .androidContract
        case "androidCreate" : self = .androidCreate
        case "androidDelete" : self = .androidDelete
        case "androidDesktop" : self = .androidDesktop
        case "androidDocument" : self = .androidDocument
        case "androidDone" : self = .androidDone
        case "androidDoneAll" : self = .androidDoneAll
        case "androidDownload" : self = .androidDownload
        case "androidDrafts" : self = .androidDrafts
        case "androidExit" : self = .androidExit
        case "androidExpand" : self = .androidExpand
        case "androidFavorite" : self = .androidFavorite
        case "androidFavoriteOutline" : self = .androidFavoriteOutline
        case "androidFilm" : self = .androidFilm
        case "androidFolder" : self = .androidFolder
        case "androidFolderOpen" : self = .androidFolderOpen
        case "androidFunnel" : self = .androidFunnel
        case "androidGlobe" : self = .androidGlobe
        case "androidHand" : self = .androidHand
        case "androidHangout" : self = .androidHangout
        case "androidHappy" : self = .androidHappy
        case "androidHome" : self = .androidHome
        case "androidImage" : self = .androidImage
        case "androidLaptop" : self = .androidLaptop
        case "androidList" : self = .androidList
        case "androidLocate" : self = .androidLocate
        case "androidLock" : self = .androidLock
        case "androidMail" : self = .androidMail
        case "androidMap" : self = .androidMap
        case "androidMenu" : self = .androidMenu
        case "androidMicrophone" : self = .androidMicrophone
        case "androidMicrophoneOff" : self = .androidMicrophoneOff
        case "androidMoreHorizontal" : self = .androidMoreHorizontal
        case "androidMoreVertical" : self = .androidMoreVertical
        case "androidNavigate" : self = .androidNavigate
        case "androidNotifications" : self = .androidNotifications
        case "androidNotificationsNone" : self = .androidNotificationsNone
        case "androidNotificationsOff" : self = .androidNotificationsOff
        case "androidOpen" : self = .androidOpen
        case "androidOptions" : self = .androidOptions
        case "androidPeople" : self = .androidPeople
        case "androidPerson" : self = .androidPerson
        case "androidPersonAdd" : self = .androidPersonAdd
        case "androidPhoneLandscape" : self = .androidPhoneLandscape
        case "androidPhonePortrait" : self = .androidPhonePortrait
        case "androidPin" : self = .androidPin
        case "androidPlane" : self = .androidPlane
        case "androidPlaystore" : self = .androidPlaystore
        case "androidPrint" : self = .androidPrint
        case "androidRadioButtonOff" : self = .androidRadioButtonOff
        case "androidRadioButtonOn" : self = .androidRadioButtonOn
        case "androidRefresh" : self = .androidRefresh
        case "androidRemove" : self = .androidRemove
        case "androidRemoveCircle" : self = .androidRemoveCircle
        case "androidRestaurant" : self = .androidRestaurant
        case "androidSad" : self = .androidSad
        case "androidSearch" : self = .androidSearch
        case "androidSend" : self = .androidSend
        case "androidSettings" : self = .androidSettings
        case "androidShare" : self = .androidShare
        case "androidShareAlt" : self = .androidShareAlt
        case "androidStar" : self = .androidStar
        case "androidStarHalf" : self = .androidStarHalf
        case "androidStarOutline" : self = .androidStarOutline
        case "androidStopwatch" : self = .androidStopwatch
        case "androidSubway" : self = .androidSubway
        case "androidSunny" : self = .androidSunny
        case "androidSync" : self = .androidSync
        case "androidTextsms" : self = .androidTextsms
        case "androidTime" : self = .androidTime
        case "androidTrain" : self = .androidTrain
        case "androidUnlock" : self = .androidUnlock
        case "androidUpload" : self = .androidUpload
        case "androidVolumeDown" : self = .androidVolumeDown
        case "androidVolumeMute" : self = .androidVolumeMute
        case "androidVolumeOff" : self = .androidVolumeOff
        case "androidVolumeUp" : self = .androidVolumeUp
        case "androidWalk" : self = .androidWalk
        case "androidWarning" : self = .androidWarning
        case "androidWatch" : self = .androidWatch
        case "androidWifi" : self = .androidWifi
        case "aperture" : self = .aperture
        case "archive" : self = .archive
        case "arrowDownA" : self = .arrowDownA
        case "arrowDownB" : self = .arrowDownB
        case "arrowDownC" : self = .arrowDownC
        case "arrowExpand" : self = .arrowExpand
        case "arrowGraphDownLeft" : self = .arrowGraphDownLeft
        case "arrowGraphDownRight" : self = .arrowGraphDownRight
        case "arrowGraphUpLeft" : self = .arrowGraphUpLeft
        case "arrowGraphUpRight" : self = .arrowGraphUpRight
        case "arrowLeftA" : self = .arrowLeftA
        case "arrowLeftB" : self = .arrowLeftB
        case "arrowLeftC" : self = .arrowLeftC
        case "arrowMove" : self = .arrowMove
        case "arrowResize" : self = .arrowResize
        case "arrowReturnLeft" : self = .arrowReturnLeft
        case "arrowReturnRight" : self = .arrowReturnRight
        case "arrowRightA" : self = .arrowRightA
        case "arrowRightB" : self = .arrowRightB
        case "arrowRightC" : self = .arrowRightC
        case "arrowShrink" : self = .arrowShrink
        case "arrowSwap" : self = .arrowSwap
        case "arrowUpA" : self = .arrowUpA
        case "arrowUpB" : self = .arrowUpB
        case "arrowUpC" : self = .arrowUpC
        case "asterisk" : self = .asterisk
        case "at" : self = .at
        case "backspace" : self = .backspace
        case "backspaceOutline" : self = .backspaceOutline
        case "bag" : self = .bag
        case "batteryCharging" : self = .batteryCharging
        case "batteryEmpty" : self = .batteryEmpty
        case "batteryFull" : self = .batteryFull
        case "batteryHalf" : self = .batteryHalf
        case "batteryLow" : self = .batteryLow
        case "beaker" : self = .beaker
        case "beer" : self = .beer
        case "bluetooth" : self = .bluetooth
        case "bonfire" : self = .bonfire
        case "bookmark" : self = .bookmark
        case "bowtie" : self = .bowtie
        case "brief=" : self = .briefcase
        case "bug" : self = .bug
        case "calculator" : self = .calculator
        case "calendar" : self = .calendar
        case "camera" : self = .camera
        case "card" : self = .card
        case "cash" : self = .cash
        case "chatbox" : self = .chatbox
        case "chatboxWorking" : self = .chatboxWorking
        case "chatboxes" : self = .chatboxes
        case "chatbubble" : self = .chatbubble
        case "chatbubbleWorking" : self = .chatbubbleWorking
        case "chatbubbles" : self = .chatbubbles
        case "checkmark" : self = .checkmark
        case "checkmarkCircled" : self = .checkmarkCircled
        case "checkmarkRound" : self = .checkmarkRound
        case "chevronDown" : self = .chevronDown
        case "chevronLeft" : self = .chevronLeft
        case "chevronRight" : self = .chevronRight
        case "chevronUp" : self = .chevronUp
        case "clipboard" : self = .clipboard
        case "clock" : self = .clock
        case "close" : self = .close
        case "closeCircled" : self = .closeCircled
        case "closeRound" : self = .closeRound
        case "closedCaptioning" : self = .closedCaptioning
        case "cloud" : self = .cloud
        case "code" : self = .code
        case "codeDownload" : self = .codeDownload
        case "codeWorking" : self = .codeWorking
        case "coffee" : self = .coffee
        case "compass" : self = .compass
        case "compose" : self = .compose
        case "connectionBars" : self = .connectionBars
        case "contrast" : self = .contrast
        case "crop" : self = .crop
        case "cube" : self = .cube
        case "disc" : self = .disc
        case "document" : self = .document
        case "documentText" : self = .documentText
        case "drag" : self = .drag
        case "earth" : self = .earth
        case "easel" : self = .easel
        case "edit" : self = .edit
        case "egg" : self = .egg
        case "eject" : self = .eject
        case "email" : self = .email
        case "emailUnread" : self = .emailUnread
        case "erlenmeyerFlask" : self = .erlenmeyerFlask
        case "erlenmeyerFlaskBubbles" : self = .erlenmeyerFlaskBubbles
        case "eye" : self = .eye
        case "eyeDisabled" : self = .eyeDisabled
        case "female" : self = .female
        case "filing" : self = .filing
        case "filmMarker" : self = .filmMarker
        case "fireball" : self = .fireball
        case "flag" : self = .flag
        case "flame" : self = .flame
        case "flash" : self = .flash
        case "flashOff" : self = .flashOff
        case "folder" : self = .folder
        case "fork" : self = .fork
        case "forkRepo" : self = .forkRepo
        case "forward" : self = .forward
        case "funnel" : self = .funnel
        case "gearA" : self = .gearA
        case "gearB" : self = .gearB
        case "grid" : self = .grid
        case "hammer" : self = .hammer
        case "happy" : self = .happy
        case "happyOutline" : self = .happyOutline
        case "headphone" : self = .headphone
        case "heart" : self = .heart
        case "heartBroken" : self = .heartBroken
        case "help" : self = .help
        case "helpBuoy" : self = .helpBuoy
        case "helpCircled" : self = .helpCircled
        case "home" : self = .home
        case "icecream" : self = .icecream
        case "image" : self = .image
        case "images" : self = .images
        case "information" : self = .information
        case "informationCircled" : self = .informationCircled
        case "ionic" : self = .ionic
        case "iosAlarm" : self = .iosAlarm
        case "iosAlarmOutline" : self = .iosAlarmOutline
        case "iosAlbums" : self = .iosAlbums
        case "iosAlbumsOutline" : self = .iosAlbumsOutline
        case "iosAmericanfootball" : self = .iosAmericanfootball
        case "iosAmericanfootballOutline" : self = .iosAmericanfootballOutline
        case "iosAnalytics" : self = .iosAnalytics
        case "iosAnalyticsOutline" : self = .iosAnalyticsOutline
        case "iosArrowBack" : self = .iosArrowBack
        case "iosArrowDown" : self = .iosArrowDown
        case "iosArrowForward" : self = .iosArrowForward
        case "iosArrowLeft" : self = .iosArrowLeft
        case "iosArrowRight" : self = .iosArrowRight
        case "iosArrowThinDown" : self = .iosArrowThinDown
        case "iosArrowThinLeft" : self = .iosArrowThinLeft
        case "iosArrowThinRight" : self = .iosArrowThinRight
        case "iosArrowThinUp" : self = .iosArrowThinUp
        case "iosArrowUp" : self = .iosArrowUp
        case "iosAt" : self = .iosAt
        case "iosAtOutline" : self = .iosAtOutline
        case "iosBarcode" : self = .iosBarcode
        case "iosBarcodeOutline" : self = .iosBarcodeOutline
        case "iosBaseball" : self = .iosBaseball
        case "iosBaseballOutline" : self = .iosBaseballOutline
        case "iosBasketball" : self = .iosBasketball
        case "iosBasketballOutline" : self = .iosBasketballOutline
        case "iosBell" : self = .iosBell
        case "iosBellOutline" : self = .iosBellOutline
        case "iosBody" : self = .iosBody
        case "iosBodyOutline" : self = .iosBodyOutline
        case "iosBolt" : self = .iosBolt
        case "iosBoltOutline" : self = .iosBoltOutline
        case "iosBook" : self = .iosBook
        case "iosBookOutline" : self = .iosBookOutline
        case "iosBookmarks" : self = .iosBookmarks
        case "iosBookmarksOutline" : self = .iosBookmarksOutline
        case "iosBox" : self = .iosBox
        case "iosBoxOutline" : self = .iosBoxOutline
        case "iosBrief=" : self = .iosBriefcase
        case "iosBriefcaseOutline" : self = .iosBriefcaseOutline
        case "iosBrowsers" : self = .iosBrowsers
        case "iosBrowsersOutline" : self = .iosBrowsersOutline
        case "iosCalculator" : self = .iosCalculator
        case "iosCalculatorOutline" : self = .iosCalculatorOutline
        case "iosCalendar" : self = .iosCalendar
        case "iosCalendarOutline" : self = .iosCalendarOutline
        case "iosCamera" : self = .iosCamera
        case "iosCameraOutline" : self = .iosCameraOutline
        case "iosCart" : self = .iosCart
        case "iosCartOutline" : self = .iosCartOutline
        case "iosChatboxes" : self = .iosChatboxes
        case "iosChatboxesOutline" : self = .iosChatboxesOutline
        case "iosChatbubble" : self = .iosChatbubble
        case "iosChatbubbleOutline" : self = .iosChatbubbleOutline
        case "iosCheckmark" : self = .iosCheckmark
        case "iosCheckmarkEmpty" : self = .iosCheckmarkEmpty
        case "iosCheckmarkOutline" : self = .iosCheckmarkOutline
        case "iosCircleFilled" : self = .iosCircleFilled
        case "iosCircleOutline" : self = .iosCircleOutline
        case "iosClock" : self = .iosClock
        case "iosClockOutline" : self = .iosClockOutline
        case "iosClose" : self = .iosClose
        case "iosCloseEmpty" : self = .iosCloseEmpty
        case "iosCloseOutline" : self = .iosCloseOutline
        case "iosCloud" : self = .iosCloud
        case "iosCloudDownload" : self = .iosCloudDownload
        case "iosCloudDownloadOutline" : self = .iosCloudDownloadOutline
        case "iosCloudOutline" : self = .iosCloudOutline
        case "iosCloudUpload" : self = .iosCloudUpload
        case "iosCloudUploadOutline" : self = .iosCloudUploadOutline
        case "iosCloudy" : self = .iosCloudy
        case "iosCloudyNight" : self = .iosCloudyNight
        case "iosCloudyNightOutline" : self = .iosCloudyNightOutline
        case "iosCloudyOutline" : self = .iosCloudyOutline
        case "iosCog" : self = .iosCog
        case "iosCogOutline" : self = .iosCogOutline
        case "iosColorFilter" : self = .iosColorFilter
        case "iosColorFilterOutline" : self = .iosColorFilterOutline
        case "iosColorWand" : self = .iosColorWand
        case "iosColorWandOutline" : self = .iosColorWandOutline
        case "iosCompose" : self = .iosCompose
        case "iosComposeOutline" : self = .iosComposeOutline
        case "iosContact" : self = .iosContact
        case "iosContactOutline" : self = .iosContactOutline
        case "iosCopy" : self = .iosCopy
        case "iosCopyOutline" : self = .iosCopyOutline
        case "iosCrop" : self = .iosCrop
        case "iosCropStrong" : self = .iosCropStrong
        case "iosDownload" : self = .iosDownload
        case "iosDownloadOutline" : self = .iosDownloadOutline
        case "iosDrag" : self = .iosDrag
        case "iosEmail" : self = .iosEmail
        case "iosEmailOutline" : self = .iosEmailOutline
        case "iosEye" : self = .iosEye
        case "iosEyeOutline" : self = .iosEyeOutline
        case "iosFastforward" : self = .iosFastforward
        case "iosFastforwardOutline" : self = .iosFastforwardOutline
        case "iosFiling" : self = .iosFiling
        case "iosFilingOutline" : self = .iosFilingOutline
        case "iosFilm" : self = .iosFilm
        case "iosFilmOutline" : self = .iosFilmOutline
        case "iosFlag" : self = .iosFlag
        case "iosFlagOutline" : self = .iosFlagOutline
        case "iosFlame" : self = .iosFlame
        case "iosFlameOutline" : self = .iosFlameOutline
        case "iosFlask" : self = .iosFlask
        case "iosFlaskOutline" : self = .iosFlaskOutline
        case "iosFlower" : self = .iosFlower
        case "iosFlowerOutline" : self = .iosFlowerOutline
        case "iosFolder" : self = .iosFolder
        case "iosFolderOutline" : self = .iosFolderOutline
        case "iosFootball" : self = .iosFootball
        case "iosFootballOutline" : self = .iosFootballOutline
        case "iosGameControllerA" : self = .iosGameControllerA
        case "iosGameControllerAOutline" : self = .iosGameControllerAOutline
        case "iosGameControllerB" : self = .iosGameControllerB
        case "iosGameControllerBOutline" : self = .iosGameControllerBOutline
        case "iosGear" : self = .iosGear
        case "iosGearOutline" : self = .iosGearOutline
        case "iosGlasses" : self = .iosGlasses
        case "iosGlassesOutline" : self = .iosGlassesOutline
        case "iosGridView" : self = .iosGridView
        case "iosGridViewOutline" : self = .iosGridViewOutline
        case "iosHeart" : self = .iosHeart
        case "iosHeartOutline" : self = .iosHeartOutline
        case "iosHelp" : self = .iosHelp
        case "iosHelpEmpty" : self = .iosHelpEmpty
        case "iosHelpOutline" : self = .iosHelpOutline
        case "iosHome" : self = .iosHome
        case "iosHomeOutline" : self = .iosHomeOutline
        case "iosInfinite" : self = .iosInfinite
        case "iosInfiniteOutline" : self = .iosInfiniteOutline
        case "iosInformation" : self = .iosInformation
        case "iosInformationEmpty" : self = .iosInformationEmpty
        case "iosInformationOutline" : self = .iosInformationOutline
        case "iosIonicOutline" : self = .iosIonicOutline
        case "iosKeypad" : self = .iosKeypad
        case "iosKeypadOutline" : self = .iosKeypadOutline
        case "iosLightbulb" : self = .iosLightbulb
        case "iosLightbulbOutline" : self = .iosLightbulbOutline
        case "iosList" : self = .iosList
        case "iosListOutline" : self = .iosListOutline
        case "iosLocation" : self = .iosLocation
        case "iosLocationOutline" : self = .iosLocationOutline
        case "iosLocked" : self = .iosLocked
        case "iosLockedOutline" : self = .iosLockedOutline
        case "iosLoop" : self = .iosLoop
        case "iosLoopStrong" : self = .iosLoopStrong
        case "iosMedical" : self = .iosMedical
        case "iosMedicalOutline" : self = .iosMedicalOutline
        case "iosMedkit" : self = .iosMedkit
        case "iosMedkitOutline" : self = .iosMedkitOutline
        case "iosMic" : self = .iosMic
        case "iosMicOff" : self = .iosMicOff
        case "iosMicOutline" : self = .iosMicOutline
        case "iosMinus" : self = .iosMinus
        case "iosMinusEmpty" : self = .iosMinusEmpty
        case "iosMinusOutline" : self = .iosMinusOutline
        case "iosMonitor" : self = .iosMonitor
        case "iosMonitorOutline" : self = .iosMonitorOutline
        case "iosMoon" : self = .iosMoon
        case "iosMoonOutline" : self = .iosMoonOutline
        case "iosMore" : self = .iosMore
        case "iosMoreOutline" : self = .iosMoreOutline
        case "iosMusicalNote" : self = .iosMusicalNote
        case "iosMusicalNotes" : self = .iosMusicalNotes
        case "iosNavigate" : self = .iosNavigate
        case "iosNavigateOutline" : self = .iosNavigateOutline
        case "iosNutrition" : self = .iosNutrition
        case "iosNutritionOutline" : self = .iosNutritionOutline
        case "iosPaper" : self = .iosPaper
        case "iosPaperOutline" : self = .iosPaperOutline
        case "iosPaperplane" : self = .iosPaperplane
        case "iosPaperplaneOutline" : self = .iosPaperplaneOutline
        case "iosPartlysunny" : self = .iosPartlysunny
        case "iosPartlysunnyOutline" : self = .iosPartlysunnyOutline
        case "iosPause" : self = .iosPause
        case "iosPauseOutline" : self = .iosPauseOutline
        case "iosPaw" : self = .iosPaw
        case "iosPawOutline" : self = .iosPawOutline
        case "iosPeople" : self = .iosPeople
        case "iosPeopleOutline" : self = .iosPeopleOutline
        case "iosPerson" : self = .iosPerson
        case "iosPersonOutline" : self = .iosPersonOutline
        case "iosPersonadd" : self = .iosPersonadd
        case "iosPersonaddOutline" : self = .iosPersonaddOutline
        case "iosPhotos" : self = .iosPhotos
        case "iosPhotosOutline" : self = .iosPhotosOutline
        case "iosPie" : self = .iosPie
        case "iosPieOutline" : self = .iosPieOutline
        case "iosPint" : self = .iosPint
        case "iosPintOutline" : self = .iosPintOutline
        case "iosPlay" : self = .iosPlay
        case "iosPlayOutline" : self = .iosPlayOutline
        case "iosPlus" : self = .iosPlus
        case "iosPlusEmpty" : self = .iosPlusEmpty
        case "iosPlusOutline" : self = .iosPlusOutline
        case "iosPricetag" : self = .iosPricetag
        case "iosPricetagOutline" : self = .iosPricetagOutline
        case "iosPricetags" : self = .iosPricetags
        case "iosPricetagsOutline" : self = .iosPricetagsOutline
        case "iosPrinter" : self = .iosPrinter
        case "iosPrinterOutline" : self = .iosPrinterOutline
        case "iosPulse" : self = .iosPulse
        case "iosPulseStrong" : self = .iosPulseStrong
        case "iosRainy" : self = .iosRainy
        case "iosRainyOutline" : self = .iosRainyOutline
        case "iosRecording" : self = .iosRecording
        case "iosRecordingOutline" : self = .iosRecordingOutline
        case "iosRedo" : self = .iosRedo
        case "iosRedoOutline" : self = .iosRedoOutline
        case "iosRefresh" : self = .iosRefresh
        case "iosRefreshEmpty" : self = .iosRefreshEmpty
        case "iosRefreshOutline" : self = .iosRefreshOutline
        case "iosReload" : self = .iosReload
        case "iosReverseCamera" : self = .iosReverseCamera
        case "iosReverseCameraOutline" : self = .iosReverseCameraOutline
        case "iosRewind" : self = .iosRewind
        case "iosRewindOutline" : self = .iosRewindOutline
        case "iosRose" : self = .iosRose
        case "iosRoseOutline" : self = .iosRoseOutline
        case "iosSearch" : self = .iosSearch
        case "iosSearchStrong" : self = .iosSearchStrong
        case "iosSettings" : self = .iosSettings
        case "iosSettingsStrong" : self = .iosSettingsStrong
        case "iosShuffle" : self = .iosShuffle
        case "iosShuffleStrong" : self = .iosShuffleStrong
        case "iosSkipbackward" : self = .iosSkipbackward
        case "iosSkipbackwardOutline" : self = .iosSkipbackwardOutline
        case "iosSkipforward" : self = .iosSkipforward
        case "iosSkipforwardOutline" : self = .iosSkipforwardOutline
        case "iosSnowy" : self = .iosSnowy
        case "iosSpeedometer" : self = .iosSpeedometer
        case "iosSpeedometerOutline" : self = .iosSpeedometerOutline
        case "iosStar" : self = .iosStar
        case "iosStarHalf" : self = .iosStarHalf
        case "iosStarOutline" : self = .iosStarOutline
        case "iosStopwatch" : self = .iosStopwatch
        case "iosStopwatchOutline" : self = .iosStopwatchOutline
        case "iosSunny" : self = .iosSunny
        case "iosSunnyOutline" : self = .iosSunnyOutline
        case "iosTelephone" : self = .iosTelephone
        case "iosTelephoneOutline" : self = .iosTelephoneOutline
        case "iosTennisball" : self = .iosTennisball
        case "iosTennisballOutline" : self = .iosTennisballOutline
        case "iosThunderstorm" : self = .iosThunderstorm
        case "iosThunderstormOutline" : self = .iosThunderstormOutline
        case "iosTime" : self = .iosTime
        case "iosTimeOutline" : self = .iosTimeOutline
        case "iosTimer" : self = .iosTimer
        case "iosTimerOutline" : self = .iosTimerOutline
        case "iosToggle" : self = .iosToggle
        case "iosToggleOutline" : self = .iosToggleOutline
        case "iosTrash" : self = .iosTrash
        case "iosTrashOutline" : self = .iosTrashOutline
        case "iosUndo" : self = .iosUndo
        case "iosUndoOutline" : self = .iosUndoOutline
        case "iosUnlocked" : self = .iosUnlocked
        case "iosUnlockedOutline" : self = .iosUnlockedOutline
        case "iosUpload" : self = .iosUpload
        case "iosUploadOutline" : self = .iosUploadOutline
        case "iosVideocam" : self = .iosVideocam
        case "iosVideocamOutline" : self = .iosVideocamOutline
        case "iosVolumeHigh" : self = .iosVolumeHigh
        case "iosVolumeLow" : self = .iosVolumeLow
        case "iosWineglass" : self = .iosWineglass
        case "iosWineglassOutline" : self = .iosWineglassOutline
        case "iosWorld" : self = .iosWorld
        case "iosWorldOutline" : self = .iosWorldOutline
        case "ipad" : self = .ipad
        case "iphone" : self = .iphone
        case "ipod" : self = .ipod
        case "jet" : self = .jet
        case "key" : self = .key
        case "knife" : self = .knife
        case "laptop" : self = .laptop
        case "leaf" : self = .leaf
        case "levels" : self = .levels
        case "lightbulb" : self = .lightbulb
        case "link" : self = .link
        case "loadA" : self = .loadA
        case "loadB" : self = .loadB
        case "loadC" : self = .loadC
        case "loadD" : self = .loadD
        case "location" : self = .location
        case "lockCombination" : self = .lockCombination
        case "locked" : self = .locked
        case "logIn" : self = .logIn
        case "logOut" : self = .logOut
        case "loop" : self = .loop
        case "magnet" : self = .magnet
        case "male" : self = .male
        case "man" : self = .man
        case "map" : self = .map
        case "medkit" : self = .medkit
        case "merge" : self = .merge
        case "micA" : self = .micA
        case "micB" : self = .micB
        case "micC" : self = .micC
        case "minus" : self = .minus
        case "minusCircled" : self = .minusCircled
        case "minusRound" : self = .minusRound
        case "modelS" : self = .modelS
        case "monitor" : self = .monitor
        case "more" : self = .more
        case "mouse" : self = .mouse
        case "musicNote" : self = .musicNote
        case "navicon" : self = .navicon
        case "naviconRound" : self = .naviconRound
        case "navigate" : self = .navigate
        case "network" : self = .network
        case "noSmoking" : self = .noSmoking
        case "nuclear" : self = .nuclear
        case "outlet" : self = .outlet
        case "paintbrush" : self = .paintbrush
        case "paintbucket" : self = .paintbucket
        case "paperAirplane" : self = .paperAirplane
        case "paperclip" : self = .paperclip
        case "pause" : self = .pause
        case "person" : self = .person
        case "personAdd" : self = .personAdd
        case "personStalker" : self = .personStalker
        case "pieGraph" : self = .pieGraph
        case "pin" : self = .pin
        case "pinpoint" : self = .pinpoint
        case "pizza" : self = .pizza
        case "plane" : self = .plane
        case "planet" : self = .planet
        case "play" : self = .play
        case "playstation" : self = .playstation
        case "plus" : self = .plus
        case "plusCircled" : self = .plusCircled
        case "plusRound" : self = .plusRound
        case "podium" : self = .podium
        case "pound" : self = .pound
        case "power" : self = .power
        case "pricetag" : self = .pricetag
        case "pricetags" : self = .pricetags
        case "printer" : self = .printer
        case "pullRequest" : self = .pullRequest
        case "qrScanner" : self = .qrScanner
        case "quote" : self = .quote
        case "radioWaves" : self = .radioWaves
        case "record" : self = .record
        case "refresh" : self = .refresh
        case "reply" : self = .reply
        case "replyAll" : self = .replyAll
        case "ribbonA" : self = .ribbonA
        case "ribbonB" : self = .ribbonB
        case "sad" : self = .sad
        case "sadOutline" : self = .sadOutline
        case "scissors" : self = .scissors
        case "search" : self = .search
        case "settings" : self = .settings
        case "share" : self = .share
        case "shuffle" : self = .shuffle
        case "skipBackward" : self = .skipBackward
        case "skipForward" : self = .skipForward
        case "socialAndroid" : self = .socialAndroid
        case "socialAndroidOutline" : self = .socialAndroidOutline
        case "socialAngular" : self = .socialAngular
        case "socialAngularOutline" : self = .socialAngularOutline
        case "socialApple" : self = .socialApple
        case "socialAppleOutline" : self = .socialAppleOutline
        case "socialBitcoin" : self = .socialBitcoin
        case "socialBitcoinOutline" : self = .socialBitcoinOutline
        case "socialBuffer" : self = .socialBuffer
        case "socialBufferOutline" : self = .socialBufferOutline
        case "socialChrome" : self = .socialChrome
        case "socialChromeOutline" : self = .socialChromeOutline
        case "socialCodepen" : self = .socialCodepen
        case "socialCodepenOutline" : self = .socialCodepenOutline
        case "socialCss3" : self = .socialCss3
        case "socialCss3Outline" : self = .socialCss3Outline
        case "socialDesignernews" : self = .socialDesignernews
        case "socialDesignernewsOutline" : self = .socialDesignernewsOutline
        case "socialDribbble" : self = .socialDribbble
        case "socialDribbbleOutline" : self = .socialDribbbleOutline
        case "socialDropbox" : self = .socialDropbox
        case "socialDropboxOutline" : self = .socialDropboxOutline
        case "socialEuro" : self = .socialEuro
        case "socialEuroOutline" : self = .socialEuroOutline
        case "socialFacebook" : self = .socialFacebook
        case "socialFacebookOutline" : self = .socialFacebookOutline
        case "socialFoursquare" : self = .socialFoursquare
        case "socialFoursquareOutline" : self = .socialFoursquareOutline
        case "socialFreebsdDevil" : self = .socialFreebsdDevil
        case "socialGithub" : self = .socialGithub
        case "socialGithubOutline" : self = .socialGithubOutline
        case "socialGoogle" : self = .socialGoogle
        case "socialGoogleOutline" : self = .socialGoogleOutline
        case "socialGoogleplus" : self = .socialGoogleplus
        case "socialGoogleplusOutline" : self = .socialGoogleplusOutline
        case "socialHackernews" : self = .socialHackernews
        case "socialHackernewsOutline" : self = .socialHackernewsOutline
        case "socialHtml5" : self = .socialHtml5
        case "socialHtml5Outline" : self = .socialHtml5Outline
        case "socialInstagram" : self = .socialInstagram
        case "socialInstagramOutline" : self = .socialInstagramOutline
        case "socialJavascript" : self = .socialJavascript
        case "socialJavascriptOutline" : self = .socialJavascriptOutline
        case "socialLinkedin" : self = .socialLinkedin
        case "socialLinkedinOutline" : self = .socialLinkedinOutline
        case "socialMarkdown" : self = .socialMarkdown
        case "socialNodejs" : self = .socialNodejs
        case "socialOctocat" : self = .socialOctocat
        case "socialPinterest" : self = .socialPinterest
        case "socialPinterestOutline" : self = .socialPinterestOutline
        case "socialPython" : self = .socialPython
        case "socialReddit" : self = .socialReddit
        case "socialRedditOutline" : self = .socialRedditOutline
        case "socialRss" : self = .socialRss
        case "socialRssOutline" : self = .socialRssOutline
        case "socialSass" : self = .socialSass
        case "socialSkype" : self = .socialSkype
        case "socialSkypeOutline" : self = .socialSkypeOutline
        case "socialSnapchat" : self = .socialSnapchat
        case "socialSnapchatOutline" : self = .socialSnapchatOutline
        case "socialTumblr" : self = .socialTumblr
        case "socialTumblrOutline" : self = .socialTumblrOutline
        case "socialTux" : self = .socialTux
        case "socialTwitch" : self = .socialTwitch
        case "socialTwitchOutline" : self = .socialTwitchOutline
        case "socialTwitter" : self = .socialTwitter
        case "socialTwitterOutline" : self = .socialTwitterOutline
        case "socialUsd" : self = .socialUsd
        case "socialUsdOutline" : self = .socialUsdOutline
        case "socialVimeo" : self = .socialVimeo
        case "socialVimeoOutline" : self = .socialVimeoOutline
        case "socialWhatsapp" : self = .socialWhatsapp
        case "socialWhatsappOutline" : self = .socialWhatsappOutline
        case "socialWindows" : self = .socialWindows
        case "socialWindowsOutline" : self = .socialWindowsOutline
        case "socialWordpress" : self = .socialWordpress
        case "socialWordpressOutline" : self = .socialWordpressOutline
        case "socialYahoo" : self = .socialYahoo
        case "socialYahooOutline" : self = .socialYahooOutline
        case "socialYen" : self = .socialYen
        case "socialYenOutline" : self = .socialYenOutline
        case "socialYoutube" : self = .socialYoutube
        case "socialYoutubeOutline" : self = .socialYoutubeOutline
        case "soupCan" : self = .soupCan
        case "soupCanOutline" : self = .soupCanOutline
        case "speakerphone" : self = .speakerphone
        case "speedometer" : self = .speedometer
        case "spoon" : self = .spoon
        case "star" : self = .star
        case "statsBars" : self = .statsBars
        case "steam" : self = .steam
        case "stop" : self = .stop
        case "thermometer" : self = .thermometer
        case "thumbsdown" : self = .thumbsdown
        case "thumbsup" : self = .thumbsup
        case "toggle" : self = .toggle
        case "toggleFilled" : self = .toggleFilled
        case "transgender" : self = .transgender
        case "trashA" : self = .trashA
        case "trashB" : self = .trashB
        case "trophy" : self = .trophy
        case "tshirt" : self = .tshirt
        case "tshirtOutline" : self = .tshirtOutline
        case "umbrella" : self = .umbrella
        case "university" : self = .university
        case "unlocked" : self = .unlocked
        case "upload" : self = .upload
        case "usb" : self = .usb
        case "videocamera" : self = .videocamera
        case "volumeHigh" : self = .volumeHigh
        case "volumeLow" : self = .volumeLow
        case "volumeMedium" : self = .volumeMedium
        case "volumeMute" : self = .volumeMute
        case "wand" : self = .wand
        case "waterdrop" : self = .waterdrop
        case "wifi" : self = .wifi
        case "wineglass" : self = .wineglass
        case "woman" : self = .woman
        case "wrench" : self = .wrench
        case "xbox" : self = .xbox
        default:
            return nil
        }
    }
}

extension Ionicons: FontFamily {
    public static let regularFont = FontConvertible(name: "Ionicons", family: "Ionicons", path: "ionicons")
}
